### ISSUE TITLE
Publishing as a crate

### ISSUE THREAD

**Issue by AspectUnk** [tnewman/dray#6]
Thank you for what you do, but there is a question. Why don't you publish it as a crate? This can be used as a good and simple out-of-the-box sftp server implementation

**Comment by tnewman** [comment]
Hi @AspectUnk,

I don't consider this to be production ready yet. I want to prove it out a bit more before I release it.

Also, I am considering rewriting the project in Go because the SSH libraries are more actively maintained.

**Comment by tnewman** [comment]
At any rate, the eventual goal is to publish this as a Helm chart, binary for popular platforms, etc. to make it easy to consume once the stability is there.

**Comment by tnewman** [comment]
I am not going to rewrite the project in Go anymore. The Rust SSH Server crate has been forked and is making great progress once again: https://github.com/warp-tech/russh

**Comment by AspectUnk** [comment]
Yep. I also released a crate for sftp server
